import Header from '@/components/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import SiteFooter from '@/components/Footer'
import { GlobalProvider } from './GlobalProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalProvider>
          <Header />
          <main id="main-content" className='p-6'>
            {children}
          </main>
          <SiteFooter />
        </GlobalProvider>
      </body>
    </html>
  )
}

